

export const stateCodes = {
    'un': "State Unassigned",
    'an': "Andaman and Nicobar Islands",
    'ap': "Andhra Pradesh",
    'ar': "Arunachal Pradesh",
    'as': "Assam",
    'br': "Bihar",
    'ch': "Chandigarh",
    'ct': "Chhattisgarh",
    'dl': "Delhi",
    'dn': "Dadra and Nagar Haveli and Daman and Diu",
    'ga': "Goa",
    'gj': "Gujarat",
    'hp': "Himachal Pradesh",
    'hr': "Haryana",
    'jh': "Jharkhand",
    'jk': "Jammu and Kashmir",
    'ka': "Karnataka",
    'kl': "Kerala",
    'la': "Ladakh",
    'ld': "Lakshadweep",
    'mh': "Maharashtra",
    'ml': "Meghalaya",
    'mn': "Manipur",
    'mp': "Madhya Pradesh",
    'mz': "Mizoram",
    'nl': "Nagaland",
    'or': "Odisha",
    'pb': "Punjab",
    'py': "Puducherry",
    'rj': "Rajasthan",
    'sk': "Sikkim",
    'tg': "Telangana",
    'tn': "Tamil Nadu",
    'tr': "Tripura",
    'up': "Uttar Pradesh",
    'ut': "Uttarakhand",
    'wb': "West Bengal",
}

